### ISSUE TITLE
Issue with signal (which I have worked around)

### ISSUE THREAD

**Issue by richard-chivers** [bachiraoun/pylocker#1]
Hi,

Just to let you know if you are running in debugmode with hot reload for example or in another thread other than main, using the module generates an error "signal only works in main thread"

In order to get around the issue you can wrap the call like this:

```
        if threading.current_thread().__class__.__name__ == "_MainThread":
           signal.signal(signal.SIGINT, self.__signal_handler)
```

Thanks for the module really useful!

**Comment by richard-chivers** [comment]
Worth saying you will not have the graceful handling of process exit, but useful for debug and similar.

**Comment by bachiraoun** [comment]
Thanks for feedback.
can you give a full example so i can take a closer look and try to fix the issue.
pylocker should be thread and process proof, at least this was my intention :)

thanks again

**Comment by bachiraoun** [comment]
Richard,
I reproduced the issue. thanks for notifying me :)
this will be fixed in the next version most likely adopting your exact solution.

**Comment by richard-chivers** [comment]
Hey, Thanks for that, sorry I didn't provide the example. Been snowed under...
